# Generated by Django 2.1.4 on 2019-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('profile_image', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=45)),
                ('phone_num', models.CharField(max_length=45)),
                ('is_banned', models.BooleanField()),
                ('detail_exist', models.BooleanField()),
            ],
        ),
    ]
